### ISSUE TITLE
技术讨论

### ISSUE THREAD

**Issue by jun-lu** [fuckpubg/AHK#1]
通过切换开火模式以达到快速瞄准的目的等等.

你好，请问 切换开火模式 以达到快速瞄准是什么原理？是否可以讨论一下，
因为我仔细看了脚本，并没有看懂这里的代码。

````

*RButton:: ; Fast Aiming
if ADS = 1
{ ; If enabled, clicks once and clicks again when button is released.
  SendInput {RButton}
  SendInput {RButton Down}
  KeyWait, RButton
  SendInput {RButton Up}
} else { ; If not, just keeps holding until button is released.
  SendInput {RButton Down}
  KeyWait, RButton
  SendInput {RButton Up}
}
Return

````

为什么上面的代码可以实现快速瞄准

**Comment by sharljimhtsin** [comment]
我觉得你可能没玩过这个游戏，所以才会这么觉得。

在游戏里，按住鼠标右键（RButton）不松开的话，是会出现一个准星的，人物也会处于一个瞄准的姿势。

这个方法被玩家称为“机瞄”，它处于不瞄准和开镜瞄准之间，提高了遭遇战中瞄准的精准度。

你贴得代码片段就是做了这个事情，它解放了玩家需要摁住 RButton 的中指，不是挺好吗？

**Comment by jun-lu** [comment]
我明白了 ，这个是腰射
