### ISSUE TITLE
new arms please

### ISSUE THREAD

**Issue by danillosilveira** [fuckpubg/AHK#2]
add no recoil for 

DP-28
AUG A3

please. tks

**Comment by sharljimhtsin** [comment]
as the README of the project said, i am not the creater of those AHK scripts.

i just collect them from the well known cheat website to here.

so sorry to can not help about it.

i suggest that you can search it by yourself on the website such as 
MPGH (https://www.mpgh.net/forum/forumdisplay.php?f=913)
or
UCheat (https://www.unknowncheats.me/forum/playerunknown-s-battlegrounds/).

hope it helpful. 

BTW, the AHK script can be detected now by battleEye, so use it at your own BAN risk.

the cheat way now possible is use the modified PAK package via soft link.(mklink of CMD)

good luck.
